url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/kube-prometheus-stack
commit: ea0e187018f2e2fb53ad51f33cbd872ddb1b1935
version: 100.0.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: crd-manifest
      addCRDValidationToMainChart: true
