template: staging

sync:
- url: https://github.com/rancher/charts.git
  branch: dev-v2.6-source
- url: https://github.com/rancher/charts.git
  branch: dev-v2.5-source
validate:
- url: https://github.com/rancher/charts.git
  branch: release-v2.6
  dropReleaseCandidates: true
helmRepo:
  cname: charts.rancher.io