url: https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-3.3.0.tgz
packageVersion: 00
releaseCandidateVersion: 01
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: crd-manifest
      addCRDValidationToMainChart: true
