annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: rancher-eks-operator-crd
apiVersion: v2
appVersion: 2.0.1
description: EKS Operator CustomResourceDefinitions
name: rancher-eks-operator-crd
version: 2.0.100-rc01
