image:
  repository: rancher/rancher-webhook
  tag: v0.2.0-alpha02
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""
  hostNetwork: false

capi:
  enabled: false

mcm:
  enabled: true