url: https://kiali.org/helm-charts/kiali-server-1.35.0.tgz
version: 100.0.0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
