# Source: https://github.com/kubernetes-sigs/vsphere-csi-driver
apiVersion: v1
data:
  "csi-migration": {{ .Values.csiMigration.enabled | quote }}
  "csi-auth-check": {{ .Values.csiAuthCheck.enabled | quote }}
  "online-volume-extend": {{ .Values.onlineVolumeExtend.enabled | quote }}
kind: ConfigMap
metadata:
  name: internal-feature-states.csi.vsphere.vmware.com
  namespace: {{ .Release.Namespace }}
