url: https://github.com/longhorn/charts.git
subdirectory: charts/longhorn
commit: b7c0b7177f8bddcfc4b338c20ed46632973ba8e9
packageVersion: 0
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true