url: https://github.com/longhorn/charts.git
subdirectory: charts/longhorn
commit: 79f6c629f999029d981a711c15e7698a89f97d65
version: 100.0.1
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
