url: https://kubernetes-charts.banzaicloud.com/charts/logging-operator-3.8.2.tgz
packageVersion: 02
releaseCandidateVersion: 01
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
