name: CI-push

on:
  push:
    branches:
      - dev-v2.5-source-alt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pull in all relevant branches
      run: git fetch origin dev-v2.5-source-alt dev-v2.5-alt main-alt
      
    - name: Checkout source branch
      run: git checkout dev-v2.5-source-alt
      
    - name: Validate 
      run: sudo make validate

    - name: Checkout staging branch
      run: git checkout origin/dev-v2.5-alt

    - name: Synchronize
      run:  sudo make sync
