apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-manifest
  namespace: {{ .Release.Namespace }}
data:
  crd-manifest.tgz:
  {{- .Files.Get "files/crd-manifest.tgz" | b64enc | indent 4 }}
